# Generated by Django 3.2.15 on 2022-10-04 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ubs', models.CharField(blank=True, max_length=255, null=True, verbose_name='UBS')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('carga_horaria', models.SmallIntegerField(default=0, verbose_name='Carga horária')),
                ('salario_base', models.CharField(blank=True, max_length=255, null=True, verbose_name='Salário base')),
                ('beneficios', models.TextField(blank=True, null=True, verbose_name='Benefícios')),
                ('especialidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Especialidade')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['-created'],
            },
        ),
    ]
