# Generated by Django 3.2.15 on 2022-10-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='vaga',
            name='especialidades',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Especialidades'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='carga_horaria',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Carga horária'),
        ),
    ]
