# Generated by Django 3.2.15 on 2022-10-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_auto_20221004_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaga',
            options={'ordering': ['-modified', '-created'], 'verbose_name': 'Vaga', 'verbose_name_plural': 'Vagas'},
        ),
        migrations.AddField(
            model_name='vaga',
            name='fonte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fonte'),
        ),
    ]
